# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /net/cremi/lnoe/espaces/travail/SE9/SIA/sia-gl-renderer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /net/cremi/lnoe/espaces/travail/SE9/SIA/sia-gl-renderer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /net/cremi/lnoe/espaces/travail/SE9/SIA/sia-gl-renderer/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source
.PHONY : package_source/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"dev\" \"runtime\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /net/cremi/lnoe/espaces/travail/SE9/SIA/sia-gl-renderer/CMakeFiles /net/cremi/lnoe/espaces/travail/SE9/SIA/sia-gl-renderer//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /net/cremi/lnoe/espaces/travail/SE9/SIA/sia-gl-renderer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sia_glrenderer

# Build rule for target.
sia_glrenderer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sia_glrenderer
.PHONY : sia_glrenderer

# fast build rule for target.
sia_glrenderer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/build
.PHONY : sia_glrenderer/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f ext_build/pmp-library/external/glfw-3.4/src/CMakeFiles/glfw.dir/build.make ext_build/pmp-library/external/glfw-3.4/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f ext_build/pmp-library/external/glfw-3.4/src/CMakeFiles/update_mappings.dir/build.make ext_build/pmp-library/external/glfw-3.4/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named check-template

# Build rule for target.
check-template: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check-template
.PHONY : check-template

# fast build rule for target.
check-template/fast:
	$(MAKE) $(MAKESILENT) -f ext_build/glbinding/CMakeFiles/check-template.dir/build.make ext_build/glbinding/CMakeFiles/check-template.dir/build
.PHONY : check-template/fast

#=============================================================================
# Target rules for targets named KHRplatform-sources

# Build rule for target.
KHRplatform-sources: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KHRplatform-sources
.PHONY : KHRplatform-sources

# fast build rule for target.
KHRplatform-sources/fast:
	$(MAKE) $(MAKESILENT) -f ext_build/glbinding/source/3rdparty/KHR/CMakeFiles/KHRplatform-sources.dir/build.make ext_build/glbinding/source/3rdparty/KHR/CMakeFiles/KHRplatform-sources.dir/build
.PHONY : KHRplatform-sources/fast

#=============================================================================
# Target rules for targets named glbinding

# Build rule for target.
glbinding: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glbinding
.PHONY : glbinding

# fast build rule for target.
glbinding/fast:
	$(MAKE) $(MAKESILENT) -f ext_build/glbinding/source/glbinding/CMakeFiles/glbinding.dir/build.make ext_build/glbinding/source/glbinding/CMakeFiles/glbinding.dir/build
.PHONY : glbinding/fast

#=============================================================================
# Target rules for targets named check-all

# Build rule for target.
check-all: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check-all
.PHONY : check-all

# fast build rule for target.
check-all/fast:
	$(MAKE) $(MAKESILENT) -f ext_build/glbinding/source/glbinding/CMakeFiles/check-all.dir/build.make ext_build/glbinding/source/glbinding/CMakeFiles/check-all.dir/build
.PHONY : check-all/fast

#=============================================================================
# Target rules for targets named check-glbinding

# Build rule for target.
check-glbinding: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check-glbinding
.PHONY : check-glbinding

# fast build rule for target.
check-glbinding/fast:
	$(MAKE) $(MAKESILENT) -f ext_build/glbinding/source/glbinding/CMakeFiles/check-glbinding.dir/build.make ext_build/glbinding/source/glbinding/CMakeFiles/check-glbinding.dir/build
.PHONY : check-glbinding/fast

#=============================================================================
# Target rules for targets named cppcheck-glbinding

# Build rule for target.
cppcheck-glbinding: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cppcheck-glbinding
.PHONY : cppcheck-glbinding

# fast build rule for target.
cppcheck-glbinding/fast:
	$(MAKE) $(MAKESILENT) -f ext_build/glbinding/source/glbinding/CMakeFiles/cppcheck-glbinding.dir/build.make ext_build/glbinding/source/glbinding/CMakeFiles/cppcheck-glbinding.dir/build
.PHONY : cppcheck-glbinding/fast

#=============================================================================
# Target rules for targets named glbinding-aux

# Build rule for target.
glbinding-aux: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glbinding-aux
.PHONY : glbinding-aux

# fast build rule for target.
glbinding-aux/fast:
	$(MAKE) $(MAKESILENT) -f ext_build/glbinding/source/glbinding-aux/CMakeFiles/glbinding-aux.dir/build.make ext_build/glbinding/source/glbinding-aux/CMakeFiles/glbinding-aux.dir/build
.PHONY : glbinding-aux/fast

#=============================================================================
# Target rules for targets named check-glbinding-aux

# Build rule for target.
check-glbinding-aux: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 check-glbinding-aux
.PHONY : check-glbinding-aux

# fast build rule for target.
check-glbinding-aux/fast:
	$(MAKE) $(MAKESILENT) -f ext_build/glbinding/source/glbinding-aux/CMakeFiles/check-glbinding-aux.dir/build.make ext_build/glbinding/source/glbinding-aux/CMakeFiles/check-glbinding-aux.dir/build
.PHONY : check-glbinding-aux/fast

#=============================================================================
# Target rules for targets named cppcheck-glbinding-aux

# Build rule for target.
cppcheck-glbinding-aux: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 cppcheck-glbinding-aux
.PHONY : cppcheck-glbinding-aux

# fast build rule for target.
cppcheck-glbinding-aux/fast:
	$(MAKE) $(MAKESILENT) -f ext_build/glbinding/source/glbinding-aux/CMakeFiles/cppcheck-glbinding-aux.dir/build.make ext_build/glbinding/source/glbinding-aux/CMakeFiles/cppcheck-glbinding-aux.dir/build
.PHONY : cppcheck-glbinding-aux/fast

#=============================================================================
# Target rules for targets named pack

# Build rule for target.
pack: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pack
.PHONY : pack

# fast build rule for target.
pack/fast:
	$(MAKE) $(MAKESILENT) -f ext_build/glbinding/deploy/CMakeFiles/pack.dir/build.make ext_build/glbinding/deploy/CMakeFiles/pack.dir/build
.PHONY : pack/fast

#=============================================================================
# Target rules for targets named pack-glbinding

# Build rule for target.
pack-glbinding: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pack-glbinding
.PHONY : pack-glbinding

# fast build rule for target.
pack-glbinding/fast:
	$(MAKE) $(MAKESILENT) -f ext_build/glbinding/deploy/CMakeFiles/pack-glbinding.dir/build.make ext_build/glbinding/deploy/CMakeFiles/pack-glbinding.dir/build
.PHONY : pack-glbinding/fast

#=============================================================================
# Target rules for targets named component_install

# Build rule for target.
component_install: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 component_install
.PHONY : component_install

# fast build rule for target.
component_install/fast:
	$(MAKE) $(MAKESILENT) -f ext_build/glbinding/deploy/CMakeFiles/component_install.dir/build.make ext_build/glbinding/deploy/CMakeFiles/component_install.dir/build
.PHONY : component_install/fast

#=============================================================================
# Target rules for targets named SOIL

# Build rule for target.
SOIL: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 SOIL
.PHONY : SOIL

# fast build rule for target.
SOIL/fast:
	$(MAKE) $(MAKESILENT) -f ext_build/SOIL2/CMakeFiles/SOIL.dir/build.make ext_build/SOIL2/CMakeFiles/SOIL.dir/build
.PHONY : SOIL/fast

#=============================================================================
# Target rules for targets named clang-format

# Build rule for target.
clang-format: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clang-format
.PHONY : clang-format

# fast build rule for target.
clang-format/fast:
	$(MAKE) $(MAKESILENT) -f ext_build/pmp-library/CMakeFiles/clang-format.dir/build.make ext_build/pmp-library/CMakeFiles/clang-format.dir/build
.PHONY : clang-format/fast

#=============================================================================
# Target rules for targets named pmp

# Build rule for target.
pmp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pmp
.PHONY : pmp

# fast build rule for target.
pmp/fast:
	$(MAKE) $(MAKESILENT) -f ext_build/pmp-library/src/pmp/CMakeFiles/pmp.dir/build.make ext_build/pmp-library/src/pmp/CMakeFiles/pmp.dir/build
.PHONY : pmp/fast

ext/pmp-library/external/imgui-1.91.8/imgui.o: ext/pmp-library/external/imgui-1.91.8/imgui.cpp.o
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui.o

# target to build an object file
ext/pmp-library/external/imgui-1.91.8/imgui.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui.cpp.o
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui.cpp.o

ext/pmp-library/external/imgui-1.91.8/imgui.i: ext/pmp-library/external/imgui-1.91.8/imgui.cpp.i
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui.i

# target to preprocess a source file
ext/pmp-library/external/imgui-1.91.8/imgui.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui.cpp.i
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui.cpp.i

ext/pmp-library/external/imgui-1.91.8/imgui.s: ext/pmp-library/external/imgui-1.91.8/imgui.cpp.s
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui.s

# target to generate assembly for a file
ext/pmp-library/external/imgui-1.91.8/imgui.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui.cpp.s
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui.cpp.s

ext/pmp-library/external/imgui-1.91.8/imgui_demo.o: ext/pmp-library/external/imgui-1.91.8/imgui_demo.cpp.o
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_demo.o

# target to build an object file
ext/pmp-library/external/imgui-1.91.8/imgui_demo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui_demo.cpp.o
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_demo.cpp.o

ext/pmp-library/external/imgui-1.91.8/imgui_demo.i: ext/pmp-library/external/imgui-1.91.8/imgui_demo.cpp.i
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_demo.i

# target to preprocess a source file
ext/pmp-library/external/imgui-1.91.8/imgui_demo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui_demo.cpp.i
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_demo.cpp.i

ext/pmp-library/external/imgui-1.91.8/imgui_demo.s: ext/pmp-library/external/imgui-1.91.8/imgui_demo.cpp.s
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_demo.s

# target to generate assembly for a file
ext/pmp-library/external/imgui-1.91.8/imgui_demo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui_demo.cpp.s
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_demo.cpp.s

ext/pmp-library/external/imgui-1.91.8/imgui_draw.o: ext/pmp-library/external/imgui-1.91.8/imgui_draw.cpp.o
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_draw.o

# target to build an object file
ext/pmp-library/external/imgui-1.91.8/imgui_draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui_draw.cpp.o
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_draw.cpp.o

ext/pmp-library/external/imgui-1.91.8/imgui_draw.i: ext/pmp-library/external/imgui-1.91.8/imgui_draw.cpp.i
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_draw.i

# target to preprocess a source file
ext/pmp-library/external/imgui-1.91.8/imgui_draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui_draw.cpp.i
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_draw.cpp.i

ext/pmp-library/external/imgui-1.91.8/imgui_draw.s: ext/pmp-library/external/imgui-1.91.8/imgui_draw.cpp.s
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_draw.s

# target to generate assembly for a file
ext/pmp-library/external/imgui-1.91.8/imgui_draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui_draw.cpp.s
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_draw.cpp.s

ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.o: ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.cpp.o
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.o

# target to build an object file
ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.cpp.o
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.cpp.o

ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.i: ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.cpp.i
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.i

# target to preprocess a source file
ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.cpp.i
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.cpp.i

ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.s: ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.cpp.s
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.s

# target to generate assembly for a file
ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.cpp.s
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.cpp.s

ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.o: ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.cpp.o
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.o

# target to build an object file
ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.cpp.o
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.cpp.o

ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.i: ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.cpp.i
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.i

# target to preprocess a source file
ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.cpp.i
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.cpp.i

ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.s: ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.cpp.s
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.s

# target to generate assembly for a file
ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.cpp.s
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.cpp.s

ext/pmp-library/external/imgui-1.91.8/imgui_tables.o: ext/pmp-library/external/imgui-1.91.8/imgui_tables.cpp.o
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_tables.o

# target to build an object file
ext/pmp-library/external/imgui-1.91.8/imgui_tables.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui_tables.cpp.o
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_tables.cpp.o

ext/pmp-library/external/imgui-1.91.8/imgui_tables.i: ext/pmp-library/external/imgui-1.91.8/imgui_tables.cpp.i
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_tables.i

# target to preprocess a source file
ext/pmp-library/external/imgui-1.91.8/imgui_tables.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui_tables.cpp.i
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_tables.cpp.i

ext/pmp-library/external/imgui-1.91.8/imgui_tables.s: ext/pmp-library/external/imgui-1.91.8/imgui_tables.cpp.s
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_tables.s

# target to generate assembly for a file
ext/pmp-library/external/imgui-1.91.8/imgui_tables.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui_tables.cpp.s
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_tables.cpp.s

ext/pmp-library/external/imgui-1.91.8/imgui_widgets.o: ext/pmp-library/external/imgui-1.91.8/imgui_widgets.cpp.o
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_widgets.o

# target to build an object file
ext/pmp-library/external/imgui-1.91.8/imgui_widgets.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui_widgets.cpp.o
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_widgets.cpp.o

ext/pmp-library/external/imgui-1.91.8/imgui_widgets.i: ext/pmp-library/external/imgui-1.91.8/imgui_widgets.cpp.i
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_widgets.i

# target to preprocess a source file
ext/pmp-library/external/imgui-1.91.8/imgui_widgets.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui_widgets.cpp.i
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_widgets.cpp.i

ext/pmp-library/external/imgui-1.91.8/imgui_widgets.s: ext/pmp-library/external/imgui-1.91.8/imgui_widgets.cpp.s
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_widgets.s

# target to generate assembly for a file
ext/pmp-library/external/imgui-1.91.8/imgui_widgets.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/ext/pmp-library/external/imgui-1.91.8/imgui_widgets.cpp.s
.PHONY : ext/pmp-library/external/imgui-1.91.8/imgui_widgets.cpp.s

src/camera.o: src/camera.cpp.o
.PHONY : src/camera.o

# target to build an object file
src/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/camera.cpp.o
.PHONY : src/camera.cpp.o

src/camera.i: src/camera.cpp.i
.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/camera.cpp.i
.PHONY : src/camera.cpp.i

src/camera.s: src/camera.cpp.s
.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/camera.cpp.s
.PHONY : src/camera.cpp.s

src/fbo.o: src/fbo.cpp.o
.PHONY : src/fbo.o

# target to build an object file
src/fbo.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/fbo.cpp.o
.PHONY : src/fbo.cpp.o

src/fbo.i: src/fbo.cpp.i
.PHONY : src/fbo.i

# target to preprocess a source file
src/fbo.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/fbo.cpp.i
.PHONY : src/fbo.cpp.i

src/fbo.s: src/fbo.cpp.s
.PHONY : src/fbo.s

# target to generate assembly for a file
src/fbo.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/fbo.cpp.s
.PHONY : src/fbo.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/mesh.o: src/mesh.cpp.o
.PHONY : src/mesh.o

# target to build an object file
src/mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/mesh.cpp.o
.PHONY : src/mesh.cpp.o

src/mesh.i: src/mesh.cpp.i
.PHONY : src/mesh.i

# target to preprocess a source file
src/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/mesh.cpp.i
.PHONY : src/mesh.cpp.i

src/mesh.s: src/mesh.cpp.s
.PHONY : src/mesh.s

# target to generate assembly for a file
src/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/mesh.cpp.s
.PHONY : src/mesh.cpp.s

src/shader.o: src/shader.cpp.o
.PHONY : src/shader.o

# target to build an object file
src/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/shader.cpp.o
.PHONY : src/shader.cpp.o

src/shader.i: src/shader.cpp.i
.PHONY : src/shader.i

# target to preprocess a source file
src/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/shader.cpp.i
.PHONY : src/shader.cpp.i

src/shader.s: src/shader.cpp.s
.PHONY : src/shader.s

# target to generate assembly for a file
src/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/shader.cpp.s
.PHONY : src/shader.cpp.s

src/trackball.o: src/trackball.cpp.o
.PHONY : src/trackball.o

# target to build an object file
src/trackball.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/trackball.cpp.o
.PHONY : src/trackball.cpp.o

src/trackball.i: src/trackball.cpp.i
.PHONY : src/trackball.i

# target to preprocess a source file
src/trackball.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/trackball.cpp.i
.PHONY : src/trackball.cpp.i

src/trackball.s: src/trackball.cpp.s
.PHONY : src/trackball.s

# target to generate assembly for a file
src/trackball.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/trackball.cpp.s
.PHONY : src/trackball.cpp.s

src/viewer.o: src/viewer.cpp.o
.PHONY : src/viewer.o

# target to build an object file
src/viewer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/viewer.cpp.o
.PHONY : src/viewer.cpp.o

src/viewer.i: src/viewer.cpp.i
.PHONY : src/viewer.i

# target to preprocess a source file
src/viewer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/viewer.cpp.i
.PHONY : src/viewer.cpp.i

src/viewer.s: src/viewer.cpp.s
.PHONY : src/viewer.s

# target to generate assembly for a file
src/viewer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sia_glrenderer.dir/build.make CMakeFiles/sia_glrenderer.dir/src/viewer.cpp.s
.PHONY : src/viewer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... KHRplatform-sources"
	@echo "... check-all"
	@echo "... check-glbinding"
	@echo "... check-glbinding-aux"
	@echo "... check-template"
	@echo "... clang-format"
	@echo "... component_install"
	@echo "... cppcheck-glbinding"
	@echo "... cppcheck-glbinding-aux"
	@echo "... pack"
	@echo "... pack-glbinding"
	@echo "... update_mappings"
	@echo "... SOIL"
	@echo "... glbinding"
	@echo "... glbinding-aux"
	@echo "... glfw"
	@echo "... pmp"
	@echo "... sia_glrenderer"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui.o"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui.i"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui.s"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui_demo.o"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui_demo.i"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui_demo.s"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui_draw.o"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui_draw.i"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui_draw.s"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.o"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.i"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui_impl_glfw.s"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.o"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.i"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui_impl_opengl3.s"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui_tables.o"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui_tables.i"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui_tables.s"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui_widgets.o"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui_widgets.i"
	@echo "... ext/pmp-library/external/imgui-1.91.8/imgui_widgets.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/fbo.o"
	@echo "... src/fbo.i"
	@echo "... src/fbo.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/mesh.o"
	@echo "... src/mesh.i"
	@echo "... src/mesh.s"
	@echo "... src/shader.o"
	@echo "... src/shader.i"
	@echo "... src/shader.s"
	@echo "... src/trackball.o"
	@echo "... src/trackball.i"
	@echo "... src/trackball.s"
	@echo "... src/viewer.o"
	@echo "... src/viewer.i"
	@echo "... src/viewer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

