name: C++ CI

on:
  push:
      branches: [ master ]
  pull_request:
      branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install cmake
        run: sudo apt install -y cmake libgl1-mesa-dev libegl1-mesa-dev libglfw3-dev libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev
      - name: configure
        run: ./configure && ./configure
      - name: make
        run: make
        working-directory: build
